### ISSUE TITLE
ArgumentError: Package ADCME not found in current path during ``fem_impose_Dirichlet_boundary_condition1(A, bd, m, n, h)``

### ISSUE THREAD

**Issue by Ricahrd-Li** [kailaix/AdFem.jl#14]
Hi there, when I run the codes below one line by one line in REPL,
```julia
using PyPlot 
using AdFem

m = 50; n = 50; h = 1/n 

A = constant(compute_fem_laplace_matrix1(m, n, h))
F = eval_f_on_gauss_pts((x,y)->2π^2*sin(π*x)*sin(π*y), m, n, h)
bd = bcnode("all", m, n, h)
A, _ = fem_impose_Dirichlet_boundary_condition1(A, bd, m, n, h)
```

during `A, _ = fem_impose_Dirichlet_boundary_condition1(A, bd, m, n, h)`

there is error:
```shell
julia> A, _ = fem_impose_Dirichlet_boundary_condition1(A, bd, m, n, h)
[ Info: /Users/lizhehao/.julia/packages/ADCME/7qIYe/deps/CustomOps/build/libadcme.dylib does not exist. Precompiling...
[ Info: Changed to directory build
JULIA=/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia
ERROR: ArgumentError: Package ADCME not found in current path:
- Run `import Pkg; Pkg.add("ADCME")` to install the ADCME package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:887
CMake Error at CMakeLists.txt:15 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:16 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:17 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:18 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:19 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:20 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:21 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:22 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:23 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:24 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:25 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:26 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:27 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:28 (list):
  list GET given empty list


Python path=
PREFIXDIR=
TF_INC=
TF_ABI=
TF_LIB_FILE=
MPI_INCLUDE_PATH and/or MPI_C_LIBRARIES is not set. MPI operators are not compiled.
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Configuring incomplete, errors occurred!
See also "/Users/lizhehao/.julia/packages/ADCME/7qIYe/deps/CustomOps/build/CMakeFiles/CMakeOutput.log".
See also "/Users/lizhehao/.julia/packages/ADCME/7qIYe/deps/CustomOps/build/CMakeFiles/CMakeError.log".
ERROR: failed process: Process(setenv(`/Users/lizhehao/.julia/packages/CMake/ULbyn/deps/usr/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/lizhehao/.julia/adcme/bin/ninja -DJULIA=/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia -DCMAKE_C_COMPILER=/Users/lizhehao/.julia/adcme/bin/clang -DCMAKE_CXX_COMPILER=/Users/lizhehao/.julia/adcme/bin/clang++ '' /Users/lizhehao/.julia/packages/ADCME/7qIYe/deps/CustomOps/`,["_CE_M=", "LSCOLORS=Gxfxcxdxbxegedabagacad", "PATH=/Users/lizhehao/Downloads/Visual Studio Code.app/Contents/Resources/app//bin:/Users/lizhehao/Desktop/learnTaichi/TaichiDev/taichi-llvm-10.0.0-macos/bin:/Users/lizhehao/opt/anaconda3/bin:/Users/lizhehao/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/ff++/mpich3/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin", "HDF5_USE_FILE_LOCKING=FALSE", "LLVM_FOLDER=/Users/lizhehao/Desktop/learnTaichi/TaichiDev/taichi-llvm-10.0.0-macos", "LD_LIBRARY_PATH=/Users/lizhehao/.julia/adcme/lib", "MKL_INTERFACE_LAYER=LP64,GNU", "USER=lizhehao", "LESS=-R", "CONDA_PROMPT_MODIFIER=(base) "  …  "TERM_PROGRAM_VERSION=440", "ZSH=/Users/lizhehao/.oh-my-zsh", "PWD=/Users/lizhehao/Desktop", "VSCODE_BIN_DIR=/Users/lizhehao/Downloads/Visual Studio Code.app/Contents/Resources/app/", "TERM_PROGRAM=Apple_Terminal", "OPENBLAS_NUM_THREADS=8", "CONDA_PREFIX=/Users/lizhehao/opt/anaconda3", "TERM_SESSION_ID=DB82D0C0-7828-4609-A04B-5F3155B895A7", "__KMP_REGISTERED_LIB_29763=0x1429ad168-cafe2d0e-libomp.dylib", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] #run#565(::Bool, ::typeof(run), ::Cmd) at ./process.jl:440
 [3] run at ./process.jl:438 [inlined]
 [4] #cmake#232(::String, ::typeof(ADCME.cmake), ::String) at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/extra.jl:73
 [5] cmake at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/extra.jl:52 [inlined] (repeats 2 times)
 [6] #241 at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/extra.jl:331 [inlined]
 [7] require_cmakecache(::ADCME.var"#241#243", ::String) at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/toolchain.jl:342
 [8] require_cmakecache at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/toolchain.jl:320 [inlined]
 [9] precompile(::Bool) at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/extra.jl:330
 [10] precompile at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/extra.jl:318 [inlined]
 [11] #load_system_op#237(::Bool, ::typeof(load_system_op), ::String, ::Bool) at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/extra.jl:253
 [12] #load_system_op at ./none:0 [inlined] (repeats 2 times)
 [13] getindex(::SparseTensor, ::Colon, ::Array{Int64,1}) at /Users/lizhehao/.julia/packages/ADCME/7qIYe/src/sparse.jl:320
 [14] fem_impose_Dirichlet_boundary_condition1(::SparseTensor, ::Array{Int64,1}, ::Int64, ::Int64, ::Float64) at /Users/lizhehao/Desktop/computer_graphics/julia/AdFem.jl-0.1.1/src/InvCore.jl:33
 [15] top-level scope at REPL[8]:1

```

But I have already added ADCME into my julia package.
When I run ``ls /Users/lizhehao/.julia/packages/ADCME/``
there are two folders: 
```
➜  Desktop ls /Users/lizhehao/.julia/packages/ADCME/
7qIYe hCmEo
```
What are these two folders used for? 

Thx for any reply.

**Comment by kailaix** [comment]
Hi, after researching a little bit, this problem usually arises when the package is not in "LOAD_PATH" (see [this post](https://discourse.julialang.org/t/problem-with-pkg-cannot-be-found-in-current-path/26492/2)). 

Do you have multiple versions of Julia on your computer? It might be possible you install ADCME using one version that's different from the one you are running (`/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia`)

**Comment by kailaix** [comment]
The two folders are your installed ADCME repository. You have two because you downloaded ADCME twice (`Pkg.add("ADCME")`).

**Comment by Ricahrd-Li** [comment]
Thanks for your reply!  
After typing ``] status`` I found package ``ADCME`` is not in the package list  (``AdFem`` is in the list while ``ADCME`` is not), then I retried ``Pkg.add("ADCME")`` and solved the problem.

**Comment by Ricahrd-Li** [comment]
## What's more important, I finally found a **very elegant** way to **easily install** and **reproduce** & visualize the demo codes of ``AdFem``, which is to use Docker + VSCode Docker extension + VSCode Jupyter extension + IJulia Jupyter kernel. 

![vscode_adfem_docker](https://user-images.githubusercontent.com/47491676/111093187-3d3be200-8573-11eb-82ab-4df78a7e6659.png)

## Here are what I have done: 
1. First, I get [Docker Official Images of Julia](https://hub.docker.com/_/julia) with ``docker pull julia`` (The Julia version I get is v"1.5.3")
2. Then, I start the container and get into Julia REPL with `` docker run -it julia_adfem``. 
3.  Then I run ``] add AdFem``, which will install dependency packages like ``ADCME`` and compile them. What is amazing here is that though the version of Julia running here is 1.5.3, the **long-waiting problem** when "Looking for TensorFlow Dynamic Libraries" (mentioned in issue https://github.com/kailaix/AdFem.jl/issues/13,  https://github.com/kailaix/ADCME.jl/issues/64) disappears! 
+ Note:  You may get some compilation error during ``] add AdFem``, like this one 
```
../CholeskyOp/CholeskyOp.h:1:10: fatal error: 'adept.h' file not found
#include "adept.h"
         ^~~~~~~~~
1 error generated.
```
Just do what I have done mentioned in issue https://github.com/kailaix/AdFem.jl/issues/13 to solve this. For other compilation errors that I have encountered, I just rerun ``use AdFem``  to recompile it and recompilation solved the problem. 

## Actually, here is my docker image [zhehaoli/julia_adfem](https://hub.docker.com/r/zhehaoli/julia_adfem), you can just pull it and run AdFem without the need to bother yourself reinstall AdFem! 

4. Then I followed [this article from Microsoft](https://devblogs.microsoft.com/python/introducing-the-jupyter-extension-for-vs-code/) and installed VSCode-insider, and used VSCode Docker extension + VSCode Jupyter extension + IJulia Jupyter kernel to connect to my Julia kernel (Then you will be able to smoothly run and visualize Julia codes in Jupyter notebook. ) Everything works like a magic.

**Comment by kailaix** [comment]
Yes, thank you very much for this tutorial. This is very helpful for others. Could you submit a pull request with your contribution? I think the best way is to have a standard-alone `.md` file in `docs/src` and have a link to it in README.md.

**Comment by Ricahrd-Li** [comment]
#15

**Comment by Ricahrd-Li** [comment]
Hi, sorry for the delay and I have already created this pull request. #15 @kailaix
